### ISSUE TITLE
"ValueError: invalid literal for int() with base 10: 'images' " during classification step

### ISSUE THREAD

**Issue by Giacomoalciatore** [Social-Evolution-and-Behavior/anTraX#30]
Welcome to anTraX - a software for tracking color tagged ants (and other insects)

==================================================================================

Traceback (most recent call last):
  File "/cluster/home/user/miniconda3/envs/antrax2/bin/antrax", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/antrax/cli.py", line 659, in main
    """)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/clize/runner.py", line 363, in run
    ret = cli(*args)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/clize/runner.py", line 262, in _cli
    return func('{0} {1}'.format(name, command), *args)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/antrax/cli.py", line 482, in classify
    c.predict_experiment(e, movlist=movlist, report=True)
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/antrax/classifier.py", line 369, in predict_experiment
    movieindex = [int(x.rstrip('.mat').split('_')[1]) for x in self.imagefiles]
  File "/cluster/home/user/miniconda3/envs/antrax2/lib/python3.6/site-packages/antrax/classifier.py", line 369, in <listcomp>
    movieindex = [int(x.rstrip('.mat').split('_')[1]) for x in self.imagefiles]
ValueError: invalid literal for int() with base 10: 'images'
Sender: LSF System <lsfadmin@eu-g1-042-4>
Subject: Job 186880930[38]: <Class_3a_v[1-56]> in cluster <euler> Exited

Job <Class_3a_v[1-56]> was submitted from host <eu-login-38> by user <user> in cluster <euler> at Mon Oct  4 14:00:09 2021
Job was executed on host(s) <4*eu-g1-042-4>, in queue <normal.24h>, as user <user> in cluster <euler> at Mon Oct  4 14:00:38 2021
</cluster/home/user> was used as the home directory.
</cluster/scratch/user/Age> was used as the working directory.
Started at Mon Oct  4 14:00:38 2021
Terminated at Mon Oct  4 14:00:49 2021
Results reported at Mon Oct  4 14:00:49 2021

**Comment by asafgal** [comment]
It seems there is a problem parsing the image filenames. Can you paste here the names of the files in the session/images folder?
