### ISSUE TITLE
problems with setting up the ffmpeg

### ISSUE THREAD

**Issue by dorigabay** [Social-Evolution-and-Behavior/anTraX#45]
Hello anTraX team.
I'm trying to run your example but I find difficulties with the ffmpeg.
I download it. installed it, and added to the PATH. I also checked, and ffmpeg is working.
But I get this error:

Error using ffinfo (line 17)
Could not locate ffprobe

Thank you very much!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
and here is the full transcript:

Z:\Dor_Gabay\ThesisProject\scripts\anTraX>antrax configure Z:/Dor_Gabay/ThesisProject/scripts/anTraX-data/JS16
2023-11-21 20:32:50.682240: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll

==================================================================================

Welcome to anTraX - a software for tracking color tagged ants (and other insects)

==================================================================================

20:33:00 -I- Reading video information from file
Warning: Escaped character '\J' is not valid. See 'doc sprintf' for supported special characters.
> In report (line 86)
In expreader/open_vid (line 389)
In expreader/fetch_frame (line 338)
In expreader/read_frame (line 263)
In trhandles/read_frame (line 415)
In antrax/set_Trck (line 410)
In antrax/set_experiment (line 344)
In antrax/startupFcn (line 1184)
In antrax>@(app)startupFcn(app,varargin{:}) (line 3567)
In appdesigner.internal.service/AppManagementService/tryCallback (line 380)
In appdesigner.internal.service/AppManagementService/runStartupFcn (line 153)
In matlab.apps/AppBase/runStartupFcn (line 43)
In antrax (line 3567)
20:33:03 -I- opening video file Z:/Dor_Gabay/ThesisProject/scripts/anTraX-data/JS16♂ideos\1_620:33:03 -E- Could not locate ffprobe
Error using ffinfo (line 17)
Could not locate ffprobe

Error in ffreader/collectInfo (line 176)
            self.info = ffinfo(self.file);

Error in ffreader (line 59)
            obj.collectInfo;

Error in expreader/open_vid (line 393)
            er.vr = er.VideoReader(er.cur_mov_name);

Error in expreader/fetch_frame (line 338)
                er.open_vid(m);

Error in expreader/read_frame (line 263)
            er.fetch_frame(t);

Error in trhandles/read_frame (line 415)
            [Trck.currfrm.CData,Trck.currfrm.dat] = Trck.er.read_frame(f);

Error in antrax/set_Trck (line 410)
            app.himage = imshow(app.Trck.read_frame(1),'Parent',app.ax);

Error in antrax/set_experiment (line 344)
            app.set_Trck();

Error in antrax/startupFcn (line 1184)
            set_experiment(app, Trck, p.Results.session)

Traceback (most recent call last):
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dorg\AppData\Local\Programs\Python\Python37\Scripts\antrax.exe\__main__.py", line 9, in <module>
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\antrax\cli.py", line 659, in main
    """)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\sigtools\modifiers.py", line 161, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\clize\runner.py", line 404, in run
    ret = cli(*args)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\clize\runner.py", line 271, in __call__
    return func(*posargs, **kwargs)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\clize\runner.py", line 313, in _cli
    return func('{0} {1}'.format(name, command), *args)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\clize\runner.py", line 271, in __call__
    return func(*posargs, **kwargs)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\antrax\cli.py", line 118, in configure
    launch_matlab_app('antrax', args, mcr=mcr)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\antrax\matlab.py", line 208, in launch_matlab_app
    app = eval('eng.' + appname + '(' + ','.join([str(a) for a in args]) + ')')
  File "<string>", line 1, in <module>
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "c:\users\dorg\appdata\local\programs\python\python37\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError:
  File C:\Program Files\MATLAB\R2021a\toolbox\matlab\appdesigner\appdesigner\runtime\+appdesigner\+internal\+service\AppManagementService.m, line 424, in AppManagementService.tryCallback

  File C:\Program Files\MATLAB\R2021a\toolbox\matlab\appdesigner\appdesigner\runtime\+appdesigner\+internal\+service\AppManagementService.m, line 153, in AppManagementService.runStartupFcn

  File C:\Program Files\MATLAB\R2021a\toolbox\matlab\appdesigner\appdesigner\runtime\+matlab\+apps\AppBase.m, line 43, in AppBase.runStartupFcn

  File Z:\Dor_Gabay\ThesisProject\scripts\anTraX\matlab\apps\antrax.mlapp, line 3567, in antrax.antrax
Could not locate ffprobe

**Comment by yohann-chemtob** [comment]
Hello @dorigabay 
Can you give me more info on your system and can you try to run: 
ffprobe -v error -show_entries format=format_name,size -of default=noprint_wrappers=1:nokey=1 'Z:/Dor_Gabay/ThesisProject/scripts/anTraX-data/JS16/videos/1_6/JS16_1.mp4'

Recheck the path of the video in my command
