### ISSUE TITLE
Problem with anTraX-MATLAB link

### ISSUE THREAD

**Issue by CyberRod19** [Social-Evolution-and-Behavior/anTraX#47]
Help, I have problems with the installation and the MATLAB-anTraX association

I have installed Python 3.8.10 in my virtual environment and I have installed anTraX inside it, but I have installed matlab outside the virtual environment folder. Could that be the problem?

Beforehand thank you very much.

This is the error:

2024-06-06 12:19:39.238575: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/rod/MATLAB_Runtime_R2024a_Update_3_glnxa64/v99/runtime/glnxa64:/home/rod/MATLAB_Runtime_R2024a_Update_3_glnxa64/v99/bin/glnxa64:/home/rod/MATLAB_Runtime_R2024a_Update_3_glnxa64/v99/sys/os/glnxa64
2024-06-06 12:19:39.238605: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

==================================================================================

Welcome to anTraX - a software for tracking color tagged ants (and other insects)

==================================================================================

Traceback (most recent call last):
  File "/home/rod/mi_entorno/bin/antrax", line 8, in <module>
    sys.exit(main())
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/antrax/cli.py", line 656, in main
    run(function_list, description="""
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/sigtools/modifiers.py", line 161, in __call__
    return self.func(*args, **kwargs)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/clize/runner.py", line 404, in run
    ret = cli(*args)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/clize/runner.py", line 271, in __call__
    return func(*posargs, **kwargs)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/clize/runner.py", line 313, in _cli
    return func('{0} {1}'.format(name, command), *args)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/clize/runner.py", line 271, in __call__
    return func(*posargs, **kwargs)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/antrax/cli.py", line 118, in configure
    launch_matlab_app('antrax', args, mcr=mcr)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/antrax/matlab.py", line 202, in launch_matlab_app
    run_mcr_function(appname, args, diary=PIPE)
  File "/home/rod/mi_entorno/lib/python3.8/site-packages/antrax/matlab.py", line 112, in run_mcr_function
    with Popen(cmd, stdout=diary, stderr=diary) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/rod/mi_entorno/lib/python3.8/site-packages/antrax/bin/antrax_glnxa64_mcr_interface'

**Comment by yohann-chemtob** [comment]
Hi,
Sorry for the slow respond, I was not getting the notifications.
No the issue is not from installing Matlab outside of conda.
You first error with 'libcudart.so.11.0' is most likely link to CUDA install issue.
The  'LD_LIBRARY_PATH: /home/rod/MATLAB_Runtime_R2024a_Update_3_glnxa64/v99/runtime/glnxa64:/home/rod/MATLAB_Runtime_R2024a_Update_3_glnxa64/v99/bin/glnxa64:/home/rod/MATLAB_Runtime_R2024a_Update_3_glnxa64/v99/sys/os/glnxa64' 
probably come from the path to matlab being incorrect.
Could you give me more info about your system and if you are using the main branch of anTraX?
